apiVersion: v1
kind: ConfigMap
metadata:
  name: go-demo-cfg
data:
  application.yaml: |+
    # Service
    environment: local
    serviceName: go-demo-2
    version: ${APP_VERSION}
    serverPort: 8080

    # DB
    mongodbHost: "mongodb-svc"
    mongodbPort: 27017